apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argos-xdr.yaml
  - argos-cti.yaml
  - argos-ai.yaml
  - argos-policy.yaml
  - argos-mcp.yaml
  - argos-soar.yaml
  - argos-cyber-range.yaml
  - argos-smartops.yaml
  - argos-observability.yaml
  - argos-evidence.yaml
